name: PlatformIO CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Setup PlatformIO in PATH
      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1
      
      # Build the PlatformIO project
      - name: Build PlatformIO project
        run: cd Software/ActualCode/Temperature-control/ && pio run

      # Copy .elf and .bin files to root directory
      - name: Copy ELF and BIN files
        run: cp Software/ActualCode/Temperature-control/.pio/build/az-delivery-devkit-v4/firmware.* Software/ActualCode/Temperature-control/
